version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/python:3.8.2
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: isac

    working_directory: ~/isac
    parallelism: 1

    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: Install global dotenv
          command: |
            pip3 install --user python-dotenv

      - run:
          name: Set DATABASE_URL
          environment:
            DATABASE_URL: mysql://root@localhost:3306/isac

      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            python3 manage.py migrate

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"

      - run:
          name: Running app
          command: |
            . venv/bin/activate
            python3 manage.py runserver

      - run:
          name: run a deploy job trigger
          command: |
            curl -X GET ${DOMAIN}/pull?password=${PASSWORD}

workflows:
  version: 2
  notify_deploy:
    jobs:
      - build